rssfeedcreator/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from rssfeedcreator.database import Column, Model, SurrogatePK, db, reference_col, relationship
from rssfeedcreator.extensions import bcrypt
from rssfeedcreator.feed.models import  Feed

user_feeds = db.Table('user_feeds',
    db.Column('feed_id', db.Integer, db.ForeignKey('feeds.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), primary_key=True)
)

class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.Binary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    feeds = db.relationship('Feed', secondary=user_feeds, lazy='subquery',
                          backref=db.backref('users', lazy=True))

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

rssfeedcreator/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

rssfeedcreator/feed/views.py
# -*- coding: utf-8 -*-
"""User views."""
import feedparser
from flask import Blueprint, render_template, request, url_for, redirect
from flask_login import current_user

from rssfeedcreator.extensions import db
from rssfeedcreator.feed.forms import FeedForm
from rssfeedcreator.feed.models import Feed
from rssfeedcreator.utils import flash_errors

blueprint = Blueprint('feed', __name__, url_prefix='/feed', static_folder='../static')


@blueprint.route('/')
@blueprint.route('/<path:feed_url>')
def index(feed_url=None):
    if feed_url is None:
        feed_url = request.args['feed_url']
        return redirect(url_for('feed.index', feed_url=feed_url))

    f = feedparser.parse(feed_url)
    if len(f.entries) == 0:
        return redirect(url_for('public.home'))

    return render_template('feed/index.html', f=f)


@blueprint.route('/get/', methods=['POST'])
def get():
    form = FeedForm(request.form)
    if not form.validate_on_submit():
        flash_errors(form)
        return redirect(url_for('public.home'))

    feed_url = form.feed_url.data
    return redirect(url_for('feed.index', feed_url=feed_url))


@blueprint.route('/add/', methods=['POST'])
def add():
    form = FeedForm(request.form)
    if not form.validate_on_submit():
        flash_errors(form)
        return redirect(url_for('public.home'))

    url = form.feed_url.data
    f = feedparser.parse(url)
    feed = Feed.query.filter_by(url=url).first() or Feed.create(url=url, title=f.feed.title, subtitle=f.feed.subtitle)
    current_user.feeds.append(feed)
    db.session.commit()
    return redirect(url_for('feed.index', feed_url=url))

rssfeedcreator/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

rssfeedcreator/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
from rssfeedcreator.feed.forms import FeedForm

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    feeds = reversed(current_user.feeds)
    form = FeedForm(request.form)

    return render_template('users/members.html', feeds=feeds, form=form)

rssfeedcreator/templates/users/add_feed.html
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form role="form" id="rssform" method="post" action="{{ url_for('feed.add') }}">
            {{ form.csrf_token }}
            <div class="input-group input-group-lg">
                <span class="input-group-addon">rss.gbeatty.com/feed/</span>
                 {{ form.feed_url(placeholder="https://www.reddit.com/r/python/.rss", class_="form-control") }}
            </div>
            <br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Add Feed</button>
            <br>
        </form>
    </div>
</div>

rssfeedcreator/templates/users/members.html
{% extends "layout.html" %}
{% block content %}

    <div class="body-content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-4">
                    <h1>Welcome {{ current_user.username }}</h1>
                </div>
            </div>
            {% include 'users/add_feed.html' %}

            <div class="row">
                <div class="col-md-6 col-md-offset-5">
                    <h2>My Feeds</h2>
                </div>
            </div>


            <div class="list-group">
                {% for feed in feeds %}

                    <a href="{{ url_for('feed.index', feed_url=feed.url) }}"
                       class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ feed.title }}</h5>
                            {#                    <small>{{ post.updated }}</small>#}
                        </div>
                        <p class="mb-1">{{ feed.subtitle }}</p>
                        <small>{{ url_for('feed.index', feed_url=feed.url) }}</small>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}